config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :registrations, only: %i[create]
  resources :sessions, only: %i[create]

  delete :logout, to: 'sessions#destroy'
  get :login, to: 'sessions#new'
  get :signup, to: 'registrations#new'

  namespace :admin do
    resources :users, except: :create
  end

  root to: 'welcome#index', constraints: ->(request) { request.session[:user_id].present? }
  root to: 'sessions#new'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  enum role: {
    user:  0,
    admin: 1
  }.freeze

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  validates :username, presence: true, uniqueness: true, length: { in: 3..20 }
  validates :email, presence: true, uniqueness: true, format: { with: EMAIL_REGEX }
  validates :password, confirmation: true
  validates :password, length: { minimum: 6 }, on: :create
  validates :role, presence: true

  scope :filter, (lambda do |filters|
    return all if filters.blank?
    filters.map { |filter, value| public_send(filter, value) }.reduce(:merge)
  end)

  scope :by_username, ->(value) { where('username ilike ?', "%#{value}%") }
  scope :by_email, ->(value) { where('email ilike ?', "%#{value}%") }
  scope :by_role, ->(roles) { where(role: roles) }
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < AdminController
    def update
      user.assign_attributes(user_params)
      if user.save
        flash[:notice] = t('.notice')
        redirect_to action: :show, params: {id: user.id}
      else
        render :edit
      end
    end

    def destroy
      User.destroy(params[:id])
      redirect_to action: :index, params: {page: current_page, filters: filter_params}
    end

    private

    delegate :per_page, to: Users
    helper_method :per_page

    def user
      @user ||= User.find(params[:id])
    end
    helper_method :user

    def users
      @users ||= filtered_users.offset((current_page - 1) * per_page).limit(per_page)
    end
    helper_method :users

    def filtered_users
      @filtered_users ||= User.filter(filter_params.to_h)
    end
    helper_method :filtered_users

    def current_page
      params.fetch(:page, 1).to_i
    end
    helper_method :current_page

    def user_params
      params.require(:user).permit(:username, :email, :role)
    end

    def filter_params
      return {} unless params[:filters]
      params.require(:filters).permit(:by_username, :by_email, by_role: []).tap do |filters|
        filters[:by_role]&.reject!(&:blank?)
      end.reject { |_, v| v.blank? }
    end
    helper_method :filter_params
  end
end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
  before_action :authenticate_admin!

  private

  def authenticate_admin!
    redirect_to root_path unless current_user&.admin?
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  helper_method :user_signed_in?
  helper_method :current_user

  private

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find_by(id: session[:user_id])
  end
  alias user_signed_in? current_user

  def authenticate_user!
    session.delete(:user_id) unless user_signed_in?
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new, alert: user.errors.full_messages.to_sentence
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  attr_reader :user
  helper_method :user
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if user&.authenticate(user_params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      @user = User.new(email: user_params[:email])
      flash.now.alert = t('.alert')
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def user
    @user ||= User.find_by(email: user_params[:email])
  end
  helper_method :user
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/admin/users/_filters.html.slim
h3= t('.title')

= form_for :filters, url: admin_users_path, method: :get, remote: true, html: {id: :filters_form} do |f|
  .field
    = f.label :by_username, t('.by_username')
    = f.text_field :by_username, value: params.dig(:filters, :by_username)
  .field
    = f.label :by_email, t('.by_email')
    = f.text_field :by_email, value: params.dig(:filters, :by_email)
  .field
    = f.label :by_role, t('.by_role')
    = f.collection_check_boxes :by_role, User.roles.keys, :to_s, :humanize, checked: params.dig(:filters, :by_role)

  .actions.text-center
    = f.submit t('.apply'), class: 'btn btn-primary'
    = link_to t('.reset'), admin_users_path, class: 'btn btn-dark'

app/views/admin/users/_form.html.slim
= form_for user, url: admin_user_path(user), method: :put, remote: true, html: { id: :admin_user_form } do |f|
  - if user.errors.any?
    .error_messages
      = user.errors.full_messages.to_sentence

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :Role
    = f.collection_radio_buttons :role, User.roles.keys, :to_s, :humanize
  .actions
    = f.submit t('.submit'), class: 'btn btn-primary'
    = link_to t('.cancel'), :back, class: 'btn btn-dark'

app/views/admin/users/_pagination.html.slim
.pagination.text-center
  => link_to_unless(current_page == 1, t('.prev_page'), admin_users_path(page: current_page - 1, filters: filter_params), class: 'btn btn-primary') {}
  - (1..((filtered_users.size / per_page) + (filtered_users.size % per_page > 0 ? 1 : 0))).each do |p|
    => link_to_unless current_page == p, p, admin_users_path(page: p, filters: filter_params), class: 'btn btn-primary' do
      span.btn.btn-primary.active= p
  => link_to_unless(filtered_users.size <= (per_page*current_page), t('.next_page'), admin_users_path(page: current_page + 1, filters: filter_params), class: 'btn btn-primary') {}

app/views/admin/users/_user.html.slim
tr id=dom_id(user)
  td = user.username
  td = user.email
  td = user.role
  td = link_to t('.show'), admin_user_path(user)
  td = link_to t('.edit'), edit_admin_user_path(user)
  td = link_to t('.delete'), admin_user_path(user, page: current_page), data: { confirm: t('.delete_confirmation') }, method: :delete, remote: true

app/views/admin/users/_user_list.html.slim
.container
  .users
    table
      thead
        tr
          th= t('.username')
          th= t('.email')
          th= t('.role')
          th
          th
          th

      tbody#users
        = render users

- if filtered_users.size > users.size
  = render 'pagination'

app/views/admin/users/edit.html.slim
h1= t('.title')

.container
  == render 'form'

app/views/admin/users/index.html.slim
h1= t('.title')
.users-wrapper
  #user_list= render 'user_list'
  .container.inline.filters= render 'filters'

app/views/admin/users/show.html.slim
h1= t('.title')
.container
  p#notice = notice
  p
    strong=> t('.username')
    = user.username
  p
    strong=> t('.email')
    = user.email
  p
    strong=> t('.role')
    = user.role

  => link_to t('.edit'), edit_admin_user_path(user)
  '|
  =< link_to t('.back'), admin_users_path

app/views/application/_header.html.slim
- if user_signed_in?
  => t('.signed_in', username: current_user.username)
  = link_to t('.logout'), logout_path, method: :delete, remote: true
  - if current_user.admin?
    =< link_to t('.users'), admin_users_path
- else
  => link_to t('.signup'), signup_path
  = link_to t('.login'), login_path

app/views/layouts/application.html.slim
html
  head
    title User Management
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header#header
      == render 'application/header'
    #main_content
      == yield

app/views/welcome/index.html.slim
h1= t('.hello', username: current_user.username)
.container.text-center= t('.lorem')